<?php

namespace App\Console\Commands;

use App\Models\Setting;
use App\Support\ContentBuilder;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Writes the site as static files: the current database content becomes
 * content.js next to site.js, site.css and the assets. Forms in a static copy
 * show their confirmation but send nothing (there is no server to receive them).
 */
class SiteExport extends Command
{
    protected $signature = 'site:export {dir=storage/app/export : Output folder} {--content-only : Write only content.js}';

    protected $description = 'Export the website with its current content as static files';

    public function handle(): int
    {
        $dir = rtrim($this->argument('dir'), '/');
        if (! str_starts_with($dir, '/')) {
            $dir = base_path($dir);
        }
        File::ensureDirectoryExists($dir);

        ContentBuilder::forget();
        $qs = ContentBuilder::get();
        File::put($dir.'/content.js', "/* Generated by php artisan site:export. Edit content in the dashboard, not here. */\nwindow.QS = ".ContentBuilder::json($qs).";\n");
        if ($this->option('content-only')) {
            $this->info("Wrote {$dir}/content.js");

            return self::SUCCESS;
        }

        foreach (['site.css', 'site.js', 'favicon.ico', 'robots.txt'] as $f) {
            File::copy(public_path($f), $dir.'/'.$f);
        }
        foreach (['assets', 'design-system', 'uploads', 'fonts'] as $d) {
            if (File::isDirectory(public_path($d))) {
                File::copyDirectory(public_path($d), $dir.'/'.$d);
            }
        }
        File::delete($dir.'/uploads/.gitignore');
        $html = view('site', ['qs' => 'null', 'description' => Setting::get('meta_description', '')])->render();
        $html = preg_replace('~<meta name="csrf-token"[^>]*>\n~', '', $html);
        $html = preg_replace('~<script>\nwindow\.QS = null;.*?</script>~s', '<script src="content.js"></script>', $html);
        $html = str_replace([url('/').'/', '?v='], ['', '?v='], $html);
        File::put($dir.'/index.html', $html);
        $this->info("Exported the site to {$dir}");

        return self::SUCCESS;
    }
}
