"""Build website/assets/iraq-map.js from geoBoundaries (IRQ, ADM1, simplified).

Source: geoBoundaries gbOpen, CC BY 4.0 - https://www.geoboundaries.org
Usage:  python website/tools/build_map.py [path/to/geojson]
        (downloads the file when no path is given)
"""

import json
import math
import os
import sys
import urllib.request

SRC = ("https://media.githubusercontent.com/media/wmgeolab/geoBoundaries/main/"
       "releaseData/gbOpen/IRQ/ADM1/geoBoundaries-IRQ-ADM1_simplified.geojson")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets",
                   "iraq-map.js")
WIDTH = 600          # viewBox width; height follows the country's aspect ratio
PAD = 8
TOLERANCE = 0.55     # Douglas-Peucker tolerance in viewBox units

# ISO code -> (English name, Arabic name, capital, Arabic capital, lat, lon)
GOVS = {
    "IQ-BG": ("Baghdad", "بغداد", "Baghdad", "بغداد", 33.315, 44.366),
    "IQ-BA": ("Basra", "البصرة", "Basra", "البصرة", 30.508, 47.783),
    "IQ-NI": ("Nineveh", "نينوى", "Mosul", "الموصل", 36.340, 43.130),
    "IQ-AR": ("Erbil", "أربيل", "Erbil", "أربيل", 36.191, 44.009),
    "IQ-SU": ("Sulaymaniyah", "السليمانية", "Sulaymaniyah", "السليمانية", 35.557, 45.435),
    "IQ-DA": ("Duhok", "دهوك", "Duhok", "دهوك", 36.867, 42.950),
    "IQ-KI": ("Kirkuk", "كركوك", "Kirkuk", "كركوك", 35.468, 44.392),
    "IQ-SD": ("Saladin", "صلاح الدين", "Tikrit", "تكريت", 34.607, 43.678),
    "IQ-DI": ("Diyala", "ديالى", "Baqubah", "بعقوبة", 33.750, 44.640),
    "IQ-AN": ("Anbar", "الأنبار", "Ramadi", "الرمادي", 33.420, 43.300),
    "IQ-BB": ("Babil", "بابل", "Hillah", "الحلة", 32.480, 44.420),
    "IQ-KA": ("Karbala", "كربلاء", "Karbala", "كربلاء", 32.616, 44.024),
    "IQ-NA": ("Najaf", "النجف", "Najaf", "النجف", 32.000, 44.330),
    "IQ-WA": ("Wasit", "واسط", "Kut", "الكوت", 32.500, 45.820),
    "IQ-QA": ("Al-Qadisiyah", "القادسية", "Diwaniyah", "الديوانية", 31.990, 44.925),
    "IQ-MA": ("Maysan", "ميسان", "Amarah", "العمارة", 31.840, 47.145),
    "IQ-DQ": ("Dhi Qar", "ذي قار", "Nasiriyah", "الناصرية", 31.050, 46.260),
    "IQ-MU": ("Al-Muthanna", "المثنى", "Samawah", "السماوة", 31.310, 45.280),
}


def rings(geom):
    polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
    for poly in polys:
        for ring in poly:
            yield ring


def dp(pts, tol):
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-9
    idx, dmax = 0, 0.0
    for i in range(1, len(pts) - 1):
        x, y = pts[i]
        d = abs(dy * x - dx * y + x2 * y1 - y2 * x1) / norm
        if d > dmax:
            idx, dmax = i, d
    if dmax <= tol:
        return [pts[0], pts[-1]]
    return dp(pts[:idx + 1], tol)[:-1] + dp(pts[idx:], tol)


def main():
    if len(sys.argv) > 1:
        data = json.load(open(sys.argv[1]))
    else:
        with urllib.request.urlopen(SRC) as r:
            data = json.load(r)
    feats = data["features"]
    lons = [p[0] for f in feats for r in rings(f["geometry"]) for p in r]
    lats = [p[1] for f in feats for r in rings(f["geometry"]) for p in r]
    k = math.cos(math.radians((min(lats) + max(lats)) / 2))
    x0, x1 = min(lons) * k, max(lons) * k
    y0, y1 = min(lats), max(lats)
    scale = (WIDTH - 2 * PAD) / (x1 - x0)
    height = round((y1 - y0) * scale + 2 * PAD)

    def proj(lon, lat):
        return (round(PAD + (lon * k - x0) * scale, 1),
                round(PAD + (y1 - lat) * scale, 1))

    out = []
    for f in feats:
        iso = f["properties"]["shapeISO"]
        en, ar, cap, cap_ar, lat, lon = GOVS[iso]
        d = []
        for ring in rings(f["geometry"]):
            raw = [proj(*p) for p in ring]
            mid = len(raw) // 2  # closed ring: simplify two open halves
            pts = dp(raw[:mid + 1], TOLERANCE)[:-1] + dp(raw[mid:], TOLERANCE)
            if len(pts) < 4:
                continue
            d.append("M" + "L".join("%g %g" % p for p in pts[:-1]) + "Z")
        cx, cy = proj(lon, lat)
        out.append({"id": iso, "en": en, "ar": ar, "cap": cap, "capAr": cap_ar,
                    "c": [cx, cy], "ll": [lat, lon], "d": "".join(d)})
    out.sort(key=lambda g: g["en"])
    js = ("/* Iraq governorates (ADM1). Source: geoBoundaries gbOpen, CC BY 4.0.\n"
          "   Generated by website/tools/build_map.py - do not edit by hand. */\n"
          "window.IRAQ_MAP = " + json.dumps({"w": WIDTH, "h": height, "govs": out},
                                             ensure_ascii=False, separators=(",", ":"))
          + ";\n")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(js)
    print("wrote", os.path.normpath(OUT), len(js) // 1024, "KB,", len(out), "governorates,",
          "viewBox 0 0 %d %d" % (WIDTH, height))


if __name__ == "__main__":
    main()
